#!/usr/bin/env bash
#Bash script that pings an IP address passed as an argument for 5 times

if [ $# -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
ip_address=$1
ping -c 5 "$ip_address"
fi
