#!/usr/bin/env bash
# This script loops from 1 to 10 and displays different messages based on the iteration number.

counter=1

# Using a while loop to iterate from 1 to 10
while [ $counter -le 10 ]
do
# Using if, elif, else statements to display different messages based on the iteration number
if [ $counter -eq 4 ]
then
echo "bad luck"
elif [ $counter -eq 8 ]
then
echo "good luck"
else
echo "Best School"
fi
((counter++))
done
