#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and different messages based on certain iterations using a case statement.

counter=1

# While loop to iterate from 1 to 20
while [ $counter -le 20 ]
do
# Case statement to display different messages based on the iteration number
case $counter in
4)
echo $counter
echo "bad luck from China"
;;
9)
echo $counter
echo "bad luck from Japan"
;;
17)
echo $counter
echo "bad luck from Italy"
;;
*)
echo $counter
;;
esac
((counter++))
done
