#!/usr/bin/env bash
# This script displays the content of the current directory in a list format,
# showing only the part of the name after the first dash.

# For loop to iterate over files in the current directory
for file in *
do
# Code below will checks if the file is not hidden and has a dash in the name
if [[ ! $file == .* && $file == *-* ]]
then
#Code below extracts and displays the part of the name after the first dash
echo "${file#*-}"
fi
done
