#!/usr/bin/env bash
#Configuring a ufw so that it blocks all incoming traffic
#except for the TCP ports of 22 (SSH), 443 (HTTPS SSL), 80 (HTTP)

sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
